parameters:
    app.rsa_public: '%env(file:resolve:RSA_PUBLIC_PATH)%'
    app.rsa_private: '%env(file:resolve:RSA_PRIVATE_PATH)%'
    images_directory: '%kernel.project_dir%/public/images'
    root_path: '%kernel.project_dir%'

services:

    _defaults:
        autowire: true
        autoconfigure: true


    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\JwtService:
        arguments:
            $privateKey: '%app.rsa_private%'
            $publicKey: '%app.rsa_public%'

    App\Security\JwtAccessHandler:
        arguments:
            $publicKey: '%app.rsa_public%'

    App\Controller\AuthenticationController:
        arguments:
            $publicKey: '%app.rsa_public%'

    App\Controller\UserController:
        arguments:
            $publicKey: '%app.rsa_public%'

    App\Service\FileUploader:
        arguments:
            $targetDirectory: '%images_directory%'

    App\Controller\TestController:
        arguments:
            $rootPath: '%kernel.project_dir%'

    App\Service\ImageLocatorService:
        arguments:
            $rootPath: '%root_path%'
