parameters:
    app.rsa_public: '%env(file:resolve:RSA_PUBLIC_PATH)%'
    app.rsa_private: '%env(file:resolve:RSA_PRIVATE_PATH)%'

services:

    _defaults:
        autowire: true
        autoconfigure: true


    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\JwtService:
        arguments:
            $privateKey: '%app.rsa_private%'

    App\Security\JwtAccessHandler:
        arguments:
            $publicKey: '%app.rsa_public%'
